
// Objective-C API for talking to the following Go packages
//
//	github.com/textileio/textile-go/mobile
//	github.com/textileio/textile-go/net
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobile_FRAMEWORK_H__
#define __Mobile_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Net.objc.h"
#include "universe.objc.h"

#endif
