// Objective-C API for talking to github.com/textileio/textile-go/net Go package.
//   gobind -lang=objc github.com/textileio/textile-go/net
//
// File is generated by gobind. Do not edit.

#ifndef __Net_H__
#define __Net_H__

@import Foundation;
#include "Universe.objc.h"


@class NetMultipartRequest;
@protocol NetNetworkService;
@class NetNetworkService;

@protocol NetNetworkService <NSObject>
// skipped method NetworkService.DisconnectFromPeer with unsupported parameter or return types

// skipped method NetworkService.HandleNewStream with unsupported parameter or return types

// skipped method NetworkService.HandlerForMsgType with unsupported parameter or return types

// skipped method NetworkService.SendMessage with unsupported parameter or return types

// skipped method NetworkService.SendRequest with unsupported parameter or return types

@end

@interface NetMultipartRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)boundary;
- (void)setBoundary:(NSString*)v;
- (NSString*)payloadPath;
- (void)setPayloadPath:(NSString*)v;
- (BOOL)addFile:(NSData*)b fname:(NSString*)fname error:(NSError**)error;
- (BOOL)finish:(NSError**)error;
- (void)init_:(NSString*)dir boundary:(NSString*)boundary;
- (NSString*)send:(NSString*)url error:(NSError**)error;
@end

@interface Net : NSObject
+ (NSError*) duplicateMessage;
+ (void) setDuplicateMessage:(NSError*)v;

@end

@class NetNetworkService;

@interface NetNetworkService : NSObject <goSeqRefInterface, NetNetworkService> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
// skipped method NetworkService.DisconnectFromPeer with unsupported parameter or return types

// skipped method NetworkService.HandleNewStream with unsupported parameter or return types

// skipped method NetworkService.HandlerForMsgType with unsupported parameter or return types

// skipped method NetworkService.SendMessage with unsupported parameter or return types

// skipped method NetworkService.SendRequest with unsupported parameter or return types

@end

#endif
