// Objective-C API for talking to github.com/textileio/textile-go/net Go package.
//   gobind -lang=objc github.com/textileio/textile-go/net
//
// File is generated by gobind. Do not edit.

#ifndef __Net_H__
#define __Net_H__

@import Foundation;
#include "Universe.objc.h"


@class NetMultipartRequest;

@interface NetMultipartRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)boundary;
- (void)setBoundary:(NSString*)v;
- (NSString*)payloadPath;
- (void)setPayloadPath:(NSString*)v;
- (BOOL)addFile:(NSData*)b fname:(NSString*)fname error:(NSError**)error;
- (BOOL)finish:(NSError**)error;
- (void)init_:(NSString*)dir boundary:(NSString*)boundary;
@end

/**
 * Length of the AES key in bytes
 */
FOUNDATION_EXPORT const int64_t NetAESKeyBytes;
/**
 * The version of the encryption algorithm used. Currently only 1 is supported
 */
FOUNDATION_EXPORT const int64_t NetCiphertextVersion;
/**
 * Length of the serialized version in bytes
 */
FOUNDATION_EXPORT const int64_t NetCiphertextVersionBytes;
/**
 * Length of the RSA encrypted secret key ciphertext in bytes
 */
FOUNDATION_EXPORT const int64_t NetEncryptedSecretKeyBytes;
/**
 * Length of nacl ephemeral public key
 */
FOUNDATION_EXPORT const int64_t NetEphemeralPublicKeyBytes;
/**
 * Length of the MAC in bytes
 */
FOUNDATION_EXPORT const int64_t NetMacBytes;
/**
 * Length of the MAC key in bytes
 */
FOUNDATION_EXPORT const int64_t NetMacKeyBytes;
/**
 * Length of nacl nonce
 */
FOUNDATION_EXPORT const int64_t NetNonceBytes;
/**
 * Length of the secret key used to generate the AES and MAC keys in bytes
 */
FOUNDATION_EXPORT const int64_t NetSecretKeyBytes;

@interface Net : NSObject
/**
 * Nacl box decryption failed
 */
+ (NSError*) boxDecryptionError;
+ (void) setBoxDecryptionError:(NSError*)v;

/**
 * The HMAC included in the ciphertext is invalid
 */
+ (NSError*) errInvalidHmac;
+ (void) setErrInvalidHmac:(NSError*)v;

/**
 * The ciphertext cannot be shorter than CiphertextVersionBytes + EncryptedSecretKeyBytes + aes.BlockSize + MacKeyBytes
 */
+ (NSError*) errShortCiphertext;
+ (void) setErrShortCiphertext:(NSError*)v;

/**
 * Satic salt used in the hdkf
 */
+ (NSData*) salt;
+ (void) setSalt:(NSData*)v;

@end

// skipped function Decrypt with unsupported parameter or return types


// skipped function Encrypt with unsupported parameter or return types


#endif
