# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TextilePhotos' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TextilePhotos

  target 'TextilePhotosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TextilePhotos-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TextilePhotos-tvOS

  target 'TextilePhotos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
