# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "TextilePhotos"
    )
  end

  desc "Push internal test build to Fabric"
  lane :adhoc do
    APP_ID = "io.textile.Wallet"
    PROFILE = "match AdHoc io.textile.Wallet"
    settings_to_override = {
      :PROVISIONING_PROFILE_SPECIFIER => PROFILE
    }
    match(type: "adhoc")
    increment_build_number(
      build_number: ENV['CIRCLE_BUILD_NUM'],
      xcodeproj: "TextilePhotos.xcodeproj"
    )
    gym(
      workspace: "TextilePhotos.xcworkspace",
      scheme: "TextilePhotos",
      xcargs: settings_to_override,
      export_method: "ad-hoc",
      export_options: {
        provisioningProfiles: {
            APP_ID => PROFILE
        }
      }
    )
    crashlytics(
      api_token: ENV['FABRIC_API_TOKEN'],
      build_secret: ENV['FABRIC_BUILD_SECRET'],
      groups: 'textile-internal'
    )
    upload_symbols_to_crashlytics(dsym_path: "./TextilePhotos.app.dSYM.zip", api_token: ENV['FABRIC_API_TOKEN'])
  end

  desc "Push a new beta build to TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # Config that came from
    # https://raw.githubusercontent.com/CircleCI-Public/circleci-demo-react-native/master/ios/fastlane/Fastfile
    # -----------------------------------------------------------------------------------------------------------
    match(type: "appstore") # more information: https://codesigning.guide
    #gym # Build your app - more options available
    #pilot
    ## sh "your_script.sh"
    ## You can also use other beta testing services here (run `fastlane actions`)

    # Config that came with fastlane init
    # ----------------------------------------------------------------------------
    versionNumber = get_version_number
    newBuildNumber = latest_testflight_build_number(version: versionNumber) + 1
    increment_build_number(
      build_number: newBuildNumber,
      xcodeproj: "TextilePhotos.xcodeproj"
    )
    gym(workspace: "TextilePhotos.xcworkspace", scheme: "TextilePhotos")
    # changelog_from_git_commits
    upload_to_testflight(skip_waiting_for_build_processing: true)
    upload_symbols_to_crashlytics(dsym_path: "./TextilePhotos.app.dSYM.zip", api_token: ENV['FABRIC_API_TOKEN'])
    add_git_tag(tag: "builds/iosbeta/" + versionNumber.to_s + "(" + newBuildNumber.to_s + ")")
    push_to_git_remote
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore") # more information: https://codesigning.guide
    # tag = ENV['CIRCLE_TAG'] # looks like ios_1.2.3_456
    # parts = tag.split('_')
    versionNumber = "0.4.9"
    increment_version_number(
      # version_number: parts[1],
      version_number: versionNumber,
      xcodeproj: "TextilePhotos.xcodeproj"
    )
    increment_build_number(
      # build_number: parts[2],
      build_number: 2,
      xcodeproj: "TextilePhotos.xcodeproj"
    )
    gym(workspace: "TextilePhotos.xcworkspace", scheme: "TextilePhotos")
    deliver(
      force: true,
      app_version: versionNumber,
      skip_app_version_update: true
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
